/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classe;

import java.awt.Font;

/**
 *
 * @author Training
 */
public class jogoAdvinha extends javax.swing.JFrame {

    /**
     * Creates new form jogoAdvinha
     */
    public jogoAdvinha() {
        initComponents();
        lblText.setText("<html>Estou pensando em um número, entre 1 e 10, consegue adivinhar?</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNum = new javax.swing.JButton();
        sNum = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblText.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        lblText.setForeground(new java.awt.Color(0, 0, 255));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("texto");
        lblText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, 80));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Adivinhe o número");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnNum.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnNum.setForeground(new java.awt.Color(0, 153, 204));
        btnNum.setText("Tentar");
        btnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumActionPerformed(evt);
            }
        });
        getContentPane().add(btnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 30));

        sNum.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        sNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        getContentPane().add(sNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/genio-cute.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/balao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumActionPerformed
        // TODO add your handling code here:
        double n = 1 + Math.random() * (11 - 1);
        int valor = (int) n;
        
        int num =  Integer.parseInt(sNum.getValue().toString());
        
        String fala1 = "<html>Acertou !!</html>";
        String fala2 = "<html>Errou, pensei no número " + valor + "</html>";
        
        String res = (valor == num)?fala1:fala2;
        //lblText.setFont(new Font("Arial", Font.BOLD, 14));
              
        lblText.setText(res);
        
        
        
    }//GEN-LAST:event_btnNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogoAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogoAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogoAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogoAdvinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogoAdvinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblText;
    private javax.swing.JSpinner sNum;
    // End of variables declaration//GEN-END:variables
}
